///Autogenerated file

import Cocoa

///Entry point for the app stylesheet
@objc public class S: NSObject {

//MARK: - Typography
	@objc public static let Typography = TypographyAppearanceProxy()
	@objc public class TypographyAppearanceProxy: NSObject {

		//MARK: small 
		private var _small: NSFont?
		private func smallProperty() -> NSFont {
			if let override = _small { return override }
			return NSFont.systemFontOfSize(12.0)
		}
		@objc public var small: NSFont {
			get { return self.smallProperty() }
			set { _small = newValue }
		}

		//MARK: medium 
		private var _medium: NSFont?
		private func mediumProperty() -> NSFont {
			if let override = _medium { return override }
			return NSFont.systemFontOfSize(18.0)
		}
		@objc public var medium: NSFont {
			get { return self.mediumProperty() }
			set { _medium = newValue }
		}
	}
//MARK: - FooView
	@objc public static let FooView = FooViewAppearanceProxy()
	@objc public class FooViewAppearanceProxy: NSObject {

		//MARK: margin 
		private var _margin: Float?
		private func marginProperty() -> Float {
			if let override = _margin { return override }
			return Float(12.0)
		}
		@objc public var margin: Float {
			get { return self.marginProperty() }
			set { _margin = newValue }
		}

		//MARK: font 
		private var _font: NSFont?
		private func fontProperty() -> NSFont {
			if let override = _font { return override }
			return Typography.smallProperty()
		}
		@objc public var font: NSFont {
			get { return self.fontProperty() }
			set { _font = newValue }
		}

		//MARK: opaque 
		private var _opaque: Bool?
		private func opaqueProperty() -> Bool {
			if let override = _opaque { return override }
			return true
		}
		@objc public var opaque: Bool {
			get { return self.opaqueProperty() }
			set { _opaque = newValue }
		}

		//MARK: textAlignment 
		private var _textAlignment: NSTextAlignment?
		private func textAlignmentProperty() -> NSTextAlignment {
			if let override = _textAlignment { return override }
			return NSTextAlignment.Center
		}
		@objc public var textAlignment: NSTextAlignment {
			get { return self.textAlignmentProperty() }
			set { _textAlignment = newValue }
		}
	}
//MARK: - Color
	@objc public static let Color = ColorAppearanceProxy()
	@objc public class ColorAppearanceProxy: NSObject {

		//MARK: blue 
		private var _blue: NSColor?
		private func blueProperty() -> NSColor {
			if let override = _blue { return override }
			return NSColor(red: 0.666667, green: 0.733333, blue: 0.8, alpha: 0.12549)
		}
		@objc public var blue: NSColor {
			get { return self.blueProperty() }
			set { _blue = newValue }
		}

		//MARK: red 
		private var _red: NSColor?
		public func redProperty() -> NSColor {
			if let override = _red { return override }
			if NSApplication.sharedApplication().mainWindow?.frame.size.width > 300.0  { 
			return NSColor(red: 1.0, green: 0.8, blue: 0.0, alpha: 1.0)
			}
			if NSApplication.sharedApplication().mainWindow?.frame.size.width < 300.0  { 
			return NSColor(red: 1.0, green: 0.8, blue: 0.0, alpha: 1.0)
			}
			
			return NSColor(red: 1.0, green: 0.8, blue: 0.0, alpha: 1.0)
		}
		@objc public var red: NSColor {
			get { return self.redProperty() }
			set { _red = newValue }
		}
	}
//MARK: - DefaultButton
	@objc public static let DefaultButton = DefaultButtonAppearanceProxy()
	@objc public class DefaultButtonAppearanceProxy: FooViewAppearanceProxy {

		//MARK: opaque 
		override private func opaqueProperty() -> Bool {
			if let override = _opaque { return override }
			return false
		}

		//MARK: margin 
		override private func marginProperty() -> Float {
			if let override = _margin { return override }
			return Float(12.0)
		}

		//MARK: color 
		private var _color: NSColor?
		private func colorProperty() -> NSColor {
			if let override = _color { return override }
			return Color.blueProperty()
		}
		@objc public var color: NSColor {
			get { return self.colorProperty() }
			set { _color = newValue }
		}
	}

}