///Autogenerated file

import UIKit

private var __ApperanceProxyHandle: UInt8 = 0

///Your view should conform to 'AppearaceProxyComponent' in order to expose an appearance proxy
public protocol AppearaceProxyComponent: class {
	typealias ApperanceProxyType
	var appearanceProxy: ApperanceProxyType { get }
	func didChangeAppearanceProxy()
}

extension AppearaceProxyComponent {
	func didChangeAppearanceProxy() { print("\(__FUNCTION__) not implemented in \(self.dynamicType)") }
}

///Entry point for the app stylesheet
public class S {

//MARK: - DefaultButton
	public static let DefaultButton = DefaultButtonAppearanceProxy()
	public class DefaultButtonAppearanceProxy: FooViewAppearanceProxy {

		//MARK: opaque 
		override private func opaqueProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> Bool {
			if let override = _opaque { return override }
			return false
		}

		//MARK: margin 
		override private func marginProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> Float {
			if let override = _margin { return override }
			return Float(12.0)
		}

		//MARK: color 
		private var _color: UIColor?
		private func colorProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIColor {
			if let override = _color { return override }
			return Color.blueProperty(traitCollection)
		}
		public var color: UIColor {
			get { return self.colorProperty() }
			set { _color = newValue }
		}
	}
//MARK: - Typography
	public static let Typography = TypographyAppearanceProxy()
	public class TypographyAppearanceProxy {

		//MARK: small 
		private var _small: UIFont?
		private func smallProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIFont {
			if let override = _small { return override }
			return UIFont(name: "Helvetica", size: 12.0)!
		}
		public var small: UIFont {
			get { return self.smallProperty() }
			set { _small = newValue }
		}

		//MARK: medium 
		private var _medium: UIFont?
		private func mediumProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIFont {
			if let override = _medium { return override }
			return UIFont(name: "Helvetica", size: 18.0)!
		}
		public var medium: UIFont {
			get { return self.mediumProperty() }
			set { _medium = newValue }
		}
	}
//MARK: - FooView
	public static let FooView = FooViewAppearanceProxy()
	public class FooViewAppearanceProxy {

		//MARK: backgroundColor 
		private var _backgroundColor: UIColor?
		private func backgroundColorProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIColor {
			if let override = _backgroundColor { return override }
			return Color.redProperty(traitCollection)
		}
		public var backgroundColor: UIColor {
			get { return self.backgroundColorProperty() }
			set { _backgroundColor = newValue }
		}

		//MARK: margin 
		private var _margin: Float?
		private func marginProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> Float {
			if let override = _margin { return override }
			return Float(12.0)
		}
		public var margin: Float {
			get { return self.marginProperty() }
			set { _margin = newValue }
		}

		//MARK: font 
		private var _font: UIFont?
		private func fontProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIFont {
			if let override = _font { return override }
			return Typography.smallProperty(traitCollection)
		}
		public var font: UIFont {
			get { return self.fontProperty() }
			set { _font = newValue }
		}

		//MARK: opaque 
		private var _opaque: Bool?
		private func opaqueProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> Bool {
			if let override = _opaque { return override }
			return true
		}
		public var opaque: Bool {
			get { return self.opaqueProperty() }
			set { _opaque = newValue }
		}
	}
//MARK: - Color
	public static let Color = ColorAppearanceProxy()
	public class ColorAppearanceProxy {

		//MARK: blue 
		private var _blue: UIColor?
		private func blueProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIColor {
			if let override = _blue { return override }
			return UIColor(red: 0.0, green: 1.0, blue: 0.0, alpha: 1.0)
		}
		public var blue: UIColor {
			get { return self.blueProperty() }
			set { _blue = newValue }
		}

		//MARK: red 
		private var _red: UIColor?
		public func redProperty(traitCollection: UITraitCollection? = UIScreen.mainScreen().traitCollection) -> UIColor {
			if let override = _red { return override }
			if UIDevice.currentDevice().userInterfaceIdiom == UIUserInterfaceIdiom.Phone  && UIScreen.mainScreen().bounds.size.width < 300.0  { 
			return UIColor(red: 0.666667, green: 0.0, blue: 0.0, alpha: 1.0)
			}
			
			return UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0)
		}
		public var red: UIColor {
			get { return self.redProperty() }
			set { _red = newValue }
		}
	}

}
extension FooView: AppearaceProxyComponent {

	 typealias ApperanceProxyType = S.FooViewAppearanceProxy
	 var appearanceProxy: ApperanceProxyType {
		get {
			guard let proxy = objc_getAssociatedObject(self, &__ApperanceProxyHandle) as? ApperanceProxyType else { return S.FooView }
			return proxy
		}
		set {
			objc_setAssociatedObject(self, &__ApperanceProxyHandle, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
			didChangeAppearanceProxy()
		}
	}
}

